{% set version = "0.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggpolypath
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggpolypath_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggpolypath/ggpolypath_{{ version }}.tar.gz
  sha256: 20f3e438b1c6d221687dbdf8063b46e0b80457f24d1c9b50723c5a051c5029c6

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2 >=2.1.0
  run:
    - r-base
    - r-ggplot2 >=2.1.0

test:
  commands:
    - $R -e "library('ggpolypath')"           # [not win]
    - "\"%R%\" -e \"library('ggpolypath')\""  # [win]

about:
  home: https://github.com/mdsumner/ggpolypath, http://rpubs.com/kohske/3522
  license: GPL-3.0-only
  summary: Tools for working with polygons with holes in 'ggplot2', with a new 'geom' for drawing a 'polypath' applying the 'evenodd' or 'winding' rules.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
